// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

// Swift Package Manager manifest file for the TrainBot project
import PackageDescription
import AppleProductTypes

let package = Package(
    name: "TrainBot", // Name of the package
    platforms: [
        .iOS("18.1") // Minimum iOS version supported
    ],
    products: [
        .iOSApplication(
            name: "TrainBot", // Name of the iOS application
            targets: ["AppModule"], // Targets included in the application
            teamIdentifier: "RK92XXY52G", // Team identifier for code signing
            displayVersion: "1.0", // Display version of the application
            bundleVersion: "1", // Bundle version of the application
            appIcon: .asset("AppIcon"), // App icon asset
            accentColor: .presetColor(.purple), // Accent color for the application
            supportedDeviceFamilies: [
                .pad, // Supported device family: iPad
                .phone // Supported device family: iPhone
            ],
            supportedInterfaceOrientations: [
                .portrait, // Supported orientation: Portrait
                .landscapeRight, // Supported orientation: Landscape Right
                .landscapeLeft, // Supported orientation: Landscape Left
                .portraitUpsideDown(.when(deviceFamilies: [.pad])) // Supported orientation: Portrait Upside Down (iPad only)
            ],
            appCategory: .education // App category: Education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule", // Main target for the TrainBot app
            path: ".", // Path to the source files
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals") // Enable upcoming Swift feature: Bare Slash Regex Literals
            ]
        )
    ]
)