import Foundation

public class DailyChallengeManager: ObservableObject {
    public static let shared = DailyChallengeManager()
    @Published public var totalPoints: Int = UserDefaults.standard.integer(forKey: "totalPoints")
    @Published public var progress: Int = 0  // New progress property
    private init() {}
    
    private let challenges: [DailyChallenge] = [
        // JANUARY (31 days)
        DailyChallenge(title: "Fresh Start", description: "Train your bot to recognize New Year decorations", category: .training, difficulty: .easy),
        DailyChallenge(title: "Winter Wonderland", description: "Collect 5 images of snow scenes", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Cozy Corner", description: "Train recognition of indoor winter items", category: .training, difficulty: .easy),
        DailyChallenge(title: "Hot Drinks", description: "Create a collection of winter beverages", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Winter Sports", description: "Train recognition of winter sports equipment", category: .training, difficulty: .medium),
        DailyChallenge(title: "Frost Patterns", description: "Collect images of frost and ice formations", category: .exploration, difficulty: .hard),
        DailyChallenge(title: "Winter Fashion", description: "Train recognition of winter clothing", category: .training, difficulty: .medium),
        DailyChallenge(title: "Indoor Plants", description: "Create a collection of houseplants", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Winter Birds", description: "Train recognition of winter birds", category: .training, difficulty: .hard),
        DailyChallenge(title: "Comfort Food", description: "Document winter comfort foods", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Snow Features", description: "Train recognition of different snow types", category: .training, difficulty: .hard),
        DailyChallenge(title: "Winter Sky", description: "Collect images of winter sky phenomena", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Indoor Games", description: "Create collection of indoor activities", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Winter Trees", description: "Train recognition of bare trees", category: .training, difficulty: .medium),
        DailyChallenge(title: "Winter Sunset", description: "Document winter sunsets", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Winter Wildlife", description: "Train recognition of winter animals", category: .training, difficulty: .hard),
        DailyChallenge(title: "Seasonal Lights", description: "Create collection of winter lighting", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Winter Weather", description: "Train weather condition recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Indoor Shadows", description: "Document interesting indoor shadows", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Winter Textures", description: "Train texture recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Comfort Corner", description: "Create cozy space collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Night Lights", description: "Train recognition of night scenes", category: .training, difficulty: .medium),
        DailyChallenge(title: "Winter Morning", description: "Document early morning winter scenes", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Indoor Art", description: "Create collection of indoor artwork", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Winter Boots", description: "Train footwear recognition", category: .training, difficulty: .easy),
        DailyChallenge(title: "Frost Patterns", description: "Document window frost patterns", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Winter Gear", description: "Create winter equipment collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Snow Activities", description: "Train recognition of snow activities", category: .training, difficulty: .medium),
        DailyChallenge(title: "Indoor Light", description: "Document indoor lighting effects", category: .exploration, difficulty: .hard),
        DailyChallenge(title: "Winter Stories", description: "Create storytelling collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Month Review", description: "Review and organize January collections", category: .organization, difficulty: .hard),
        
        // FEBRUARY (29 days)
        DailyChallenge(title: "Love Letters", description: "Train recognition of romantic symbols", category: .training, difficulty: .easy),
        DailyChallenge(title: "Winter's End", description: "Document signs of winter ending", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Heart Hunt", description: "Find heart shapes in everyday objects", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Candy Collection", description: "Train recognition of Valentine's candy", category: .training, difficulty: .easy),
        DailyChallenge(title: "Red & Pink", description: "Create collection of Valentine's colors", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Love Notes", description: "Train handwriting recognition of love notes", category: .training, difficulty: .hard),
        DailyChallenge(title: "Flower Power", description: "Document different types of flowers", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Gift Wrap", description: "Train recognition of gift packaging", category: .training, difficulty: .medium),
        DailyChallenge(title: "Sweet Treats", description: "Create collection of desserts", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Cupid's Arrow", description: "Train recognition of Valentine symbols", category: .training, difficulty: .medium),
        DailyChallenge(title: "Romance Movies", description: "Document romantic movie scenes", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Love Songs", description: "Create playlist cover collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Valentine Cards", description: "Train card design recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Love Day", description: "Special Valentine's Day challenge", category: .exploration, difficulty: .hard),
        DailyChallenge(title: "Date Night", description: "Create romantic setting collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Winter Farewell", description: "Document last winter scenes", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Chocolate Box", description: "Train chocolate type recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Love Letters", description: "Create collection of written expressions", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Couple Goals", description: "Train recognition of couple activities", category: .training, difficulty: .medium),
        DailyChallenge(title: "Romance Books", description: "Document romantic book covers", category: .exploration, difficulty: .easy),
        DailyChallenge(title: "Love Symbols", description: "Create symbol collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Sweet Messages", description: "Train text recognition on candy hearts", category: .training, difficulty: .hard),
        DailyChallenge(title: "Date Ideas", description: "Document romantic locations", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Love Music", description: "Create music-themed collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Romance Art", description: "Train recognition of romantic art", category: .training, difficulty: .hard),
        DailyChallenge(title: "Spring Signs", description: "Document early spring indicators", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Memory Lane", description: "Create collection of memories", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Love Letters", description: "Train handwriting recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Leap Day", description: "Special four-year challenge", category: .exploration, difficulty: .hard),
        
        // MARCH (31 days)
        DailyChallenge(title: "Spring Welcome", description: "Train recognition of early spring signs", category: .training, difficulty: .medium),
        DailyChallenge(title: "Green Beginnings", description: "Document first spring shoots", category: .exploration, difficulty: .easy),
        DailyChallenge(title: "Bird Watch", description: "Train recognition of returning birds", category: .training, difficulty: .hard),
        DailyChallenge(title: "Rain Patterns", description: "Create collection of rain effects", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Melting Snow", description: "Document snow melting patterns", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Spring Fashion", description: "Train recognition of spring clothing", category: .training, difficulty: .easy),
        DailyChallenge(title: "Garden Prep", description: "Create garden planning collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Cloud Shapes", description: "Train cloud pattern recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Spring Colors", description: "Document emerging spring colors", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Seed Starting", description: "Create seedling collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Weather Watch", description: "Train weather pattern recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Puddle Play", description: "Document reflection patterns", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Spring Clean", description: "Create organization system", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Wind Dance", description: "Train movement recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Spring Buds", description: "Document emerging plant life", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Lucky Green", description: "Train recognition of green shades", category: .training, difficulty: .medium),
        DailyChallenge(title: "St. Patrick's", description: "Create Irish symbol collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Rainbow Hunt", description: "Document sky phenomena", category: .exploration, difficulty: .hard),
        DailyChallenge(title: "Spring Light", description: "Train light pattern recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Equinox", description: "First day of Spring special challenge", category: .exploration, difficulty: .hard),
        DailyChallenge(title: "Garden Tools", description: "Create gardening collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Nest Watch", description: "Train bird nest recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Spring Shadows", description: "Document changing shadows", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Outdoor Prep", description: "Create outdoor activity collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Insect Return", description: "Train insect recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Morning Frost", description: "Document late frost patterns", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Spring Sport", description: "Create sports equipment collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Flower Watch", description: "Train flower recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Spring Sky", description: "Document sky colors", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Garden Plan", description: "Create garden layout collection", category: .organization, difficulty: .hard),
        DailyChallenge(title: "March Review", description: "Review and organize March collections", category: .organization, difficulty: .hard),
                
        // APRIL (30 days)
        DailyChallenge(title: "April Showers", description: "Train rain pattern recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Easter Eggs", description: "Create collection of decorated eggs", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Spring Flowers", description: "Train flower species recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Bunny Hunt", description: "Document rabbit sightings", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Easter Basket", description: "Train recognition of Easter items", category: .training, difficulty: .easy),
        DailyChallenge(title: "April Growth", description: "Document plant growth stages", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Spring Garden", description: "Create garden progress collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Rain Dance", description: "Train water movement recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Easter Joy", description: "Document celebration moments", category: .exploration, difficulty: .easy),
        DailyChallenge(title: "Spring Clean", description: "Create cleaning routine collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Bloom Time", description: "Train blooming stage recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Rainbow Sky", description: "Document sky after rain", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Spring Style", description: "Create spring fashion collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Bird Songs", description: "Train bird species recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Morning Dew", description: "Document water droplet patterns", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Garden Tools", description: "Create gardening equipment collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Butterfly Watch", description: "Train butterfly recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Spring Wind", description: "Document wind effects", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Picnic Prep", description: "Create outdoor dining collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Earth Colors", description: "Train natural color recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Earth Day", description: "Document environmental actions", category: .exploration, difficulty: .hard),
        DailyChallenge(title: "Green Living", description: "Create eco-friendly collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Tree Buds", description: "Train tree species recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Cloud Watch", description: "Document cloud formations", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Spring Sports", description: "Create outdoor activities collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Nest Building", description: "Train nest recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Spring Magic", description: "Document magical moments", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Garden Joy", description: "Create garden beauty collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Nature's Art", description: "Train pattern recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "April Review", description: "Review and organize April collections", category: .organization, difficulty: .hard),
        
        // MAY (31 days)
        DailyChallenge(title: "May Flowers", description: "Train recognition of May blooms", category: .training, difficulty: .medium),
        DailyChallenge(title: "Morning Sun", description: "Document early morning light", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Garden Love", description: "Create garden progress collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Bee Watch", description: "Train bee species recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Spring Birds", description: "Document nesting activities", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Flower Art", description: "Create floral arrangement collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Mom's Day Prep", description: "Train gift recognition", category: .training, difficulty: .easy),
        DailyChallenge(title: "Mother's Love", description: "Document moments with mom", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Family Time", description: "Create family activity collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Spring Fruits", description: "Train fruit recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Garden Growth", description: "Document plant progress", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Nature's Home", description: "Create wildlife habitat collection", category: .organization, difficulty: .hard),
        DailyChallenge(title: "Butterfly Dance", description: "Train butterfly movement patterns", category: .training, difficulty: .hard),
        DailyChallenge(title: "Spring Rain", description: "Document rain effects", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Outdoor Fun", description: "Create activity collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Insect Life", description: "Train insect recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Evening Light", description: "Document sunset colors", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Garden Tools", description: "Create tool organization system", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Tree Study", description: "Train leaf pattern recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Cloud Watch", description: "Document cloud formations", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Nature's Art", description: "Create natural pattern collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Bird Songs", description: "Train bird call recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Spring Sport", description: "Document outdoor activities", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Memorial Day", description: "Create patriotic collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Flag Watch", description: "Train flag recognition", category: .training, difficulty: .easy),
        DailyChallenge(title: "Honor Heroes", description: "Document memorial sites", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Summer Prep", description: "Create summer planning collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Water Fun", description: "Train water activity recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Late Spring", description: "Document transition to summer", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "BBQ Time", description: "Create outdoor cooking collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "May Review", description: "Review and organize May collections", category: .organization, difficulty: .hard),
        
        // JUNE (30 days)
        DailyChallenge(title: "Summer Start", description: "Train recognition of summer signs", category: .training, difficulty: .medium),
        DailyChallenge(title: "Garden Peak", description: "Document garden full bloom", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Pool Time", description: "Create swimming collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Dad's Tools", description: "Train tool recognition for Father's Day", category: .training, difficulty: .hard),
        DailyChallenge(title: "Summer Sky", description: "Document cloud patterns", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Beach Prep", description: "Create beach essentials collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Father's Day", description: "Train dad activity recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Family Fun", description: "Document family moments", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Summer Sports", description: "Create outdoor games collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Night Stars", description: "Train star pattern recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "School's Out", description: "Document graduation events", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Summer Plans", description: "Create vacation planning collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Beach Life", description: "Train beach object recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Summer Heat", description: "Document heat wave effects", category: .exploration, difficulty: .hard),
        DailyChallenge(title: "Picnic Time", description: "Create outdoor dining collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Water Fun", description: "Train water activity recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Long Days", description: "Document summer solstice", category: .exploration, difficulty: .hard),
        DailyChallenge(title: "Garden Harvest", description: "Create vegetable collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Bug Study", description: "Train insect recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Summer Light", description: "Document light patterns", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "BBQ Master", description: "Create grilling collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Bird Watch", description: "Train summer bird recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Summer Fun", description: "Document outdoor activities", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Camping Gear", description: "Create outdoor equipment collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Night Life", description: "Train nocturnal creature recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Beach Art", description: "Document sand patterns", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Summer Style", description: "Create summer fashion collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Sunset Watch", description: "Train sunset color recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Water Play", description: "Document splash patterns", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "June Review", description: "Review and organize June collections", category: .organization, difficulty: .hard),
        
        // JULY (31 days)
        DailyChallenge(title: "Fireworks", description: "Train recognition of firework patterns", category: .training, difficulty: .hard),
        DailyChallenge(title: "Patriotic Pride", description: "Document Independence Day celebrations", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Flag Collection", description: "Create collection of American flags", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Summer Party", description: "Train party decoration recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "BBQ Master", description: "Document grilling techniques", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Parade Time", description: "Create parade moments collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Heat Wave", description: "Train temperature effect recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Beach Day", description: "Document beach activities", category: .exploration, difficulty: .easy),
        DailyChallenge(title: "Summer Games", description: "Create outdoor games collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Ice Cream", description: "Train frozen treat recognition", category: .training, difficulty: .easy),
        DailyChallenge(title: "Water Fun", description: "Document pool activities", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Vacation Prep", description: "Create travel essentials collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Night Sky", description: "Train star pattern recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Summer Flora", description: "Document flowering plants", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Outdoor Living", description: "Create patio setup collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Sun Safety", description: "Train sun protection recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Garden Peak", description: "Document garden harvest", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Summer Style", description: "Create summer fashion collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Bug Watch", description: "Train insect species recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Cloud Study", description: "Document cloud formations", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Beach Gear", description: "Create beach equipment collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Night Life", description: "Train nocturnal animal recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Summer Storm", description: "Document weather patterns", category: .exploration, difficulty: .hard),
        DailyChallenge(title: "Picnic Plans", description: "Create outdoor dining collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Bird Watch", description: "Train summer bird recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Water Play", description: "Document splash patterns", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Camping Fun", description: "Create camping gear collection", category: .organization, difficulty: .hard),
        DailyChallenge(title: "Summer Sport", description: "Train sports equipment recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Sunset Views", description: "Document evening colors", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Cool Treats", description: "Create summer dessert collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "July Review", description: "Review and organize July collections", category: .organization, difficulty: .hard),
        
        // AUGUST (31 days)
        DailyChallenge(title: "Back to School", description: "Create school supplies collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Late Summer", description: "Train summer flower recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "School Prep", description: "Document classroom setup", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Study Space", description: "Create learning environment collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Heat Wave", description: "Train heat effect recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Water Fun", description: "Document pool activities", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Summer End", description: "Create summer memories collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Garden Harvest", description: "Train vegetable recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Storm Watch", description: "Document weather patterns", category: .exploration, difficulty: .hard),
        DailyChallenge(title: "School Style", description: "Create fashion collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Night Sky", description: "Train constellation recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Beach Days", description: "Document last beach visits", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Lunch Prep", description: "Create meal planning collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Book Smart", description: "Train textbook recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Morning Rush", description: "Document school routines", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Study Tools", description: "Create study supplies collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Late Blooms", description: "Train late flower recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Evening Light", description: "Document changing daylight", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Sports Gear", description: "Create fall sports collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Weather Watch", description: "Train weather pattern recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Garden End", description: "Document final harvests", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Fall Preview", description: "Create autumn preview collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Bird Watch", description: "Train migrating bird recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Sunset Study", description: "Document earlier sunsets", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Home Study", description: "Create homework space collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Bug Watch", description: "Train late insect recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Cloud Patterns", description: "Document changing weather", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Class Ready", description: "Create classroom collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Night Changes", description: "Train evening light recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Season Shift", description: "Document seasonal changes", category: .exploration, difficulty: .hard),
        DailyChallenge(title: "August Review", description: "Review and organize August collections", category: .organization, difficulty: .hard),
        
        // SEPTEMBER (30 days)
        DailyChallenge(title: "Fall Begin", description: "Document early autumn signs", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Harvest Time", description: "Train fruit recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Labor Day", description: "Create holiday activity collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "School Life", description: "Train classroom object recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Morning Fog", description: "Document autumn morning mist", category: .exploration, difficulty: .hard),
        DailyChallenge(title: "Fall Fashion", description: "Create autumn wardrobe collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Leaf Watch", description: "Train early color changes", category: .training, difficulty: .medium),
        DailyChallenge(title: "Apple Time", description: "Document apple varieties", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Study Space", description: "Create homework station collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Migration", description: "Train bird migration patterns", category: .training, difficulty: .hard),
        DailyChallenge(title: "Cool Mornings", description: "Document temperature changes", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Fall Sports", description: "Create sports equipment collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Garden End", description: "Train late harvest recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Autumn Sky", description: "Document cloud formations", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Cozy Corner", description: "Create reading nook collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Night Watch", description: "Train evening light patterns", category: .training, difficulty: .hard),
        DailyChallenge(title: "Fall Colors", description: "Document changing leaves", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Weather Prep", description: "Create fall weather gear collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Harvest Moon", description: "Train night sky recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Fall Garden", description: "Document garden cleanup", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Study Time", description: "Create study schedule collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Fall Birds", description: "Train autumn bird recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Early Sunset", description: "Document shorter days", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Fall Decor", description: "Create autumn decoration collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Weather Watch", description: "Train weather pattern recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Nature Walk", description: "Document fall nature changes", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Autumn Spice", description: "Create fall recipe collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Evening Study", description: "Train indoor light recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Autumn Art", description: "Document fall crafts", category: .exploration, difficulty: .easy),
        DailyChallenge(title: "September Review", description: "Review and organize September collections", category: .organization, difficulty: .hard),
        
        // OCTOBER (31 days)
        DailyChallenge(title: "October Start", description: "Train fall color recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Pumpkin Patch", description: "Document pumpkin varieties", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Halloween Prep", description: "Create costume collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Fall Peak", description: "Train foliage recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Morning Frost", description: "Document first frost patterns", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Cozy Drinks", description: "Create hot beverage collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Scary Faces", description: "Train jack-o'-lantern recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Fall Harvest", description: "Document crop gathering", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Costume Time", description: "Create Halloween outfit collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Night Creatures", description: "Train nocturnal animal recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Foggy Days", description: "Document misty mornings", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Fall Treats", description: "Create autumn recipe collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Spooky Lights", description: "Train Halloween light recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Autumn Rain", description: "Document rainy day patterns", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Indoor Fun", description: "Create rainy day activity collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Fall Birds", description: "Train migrating bird recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Leaf Carpet", description: "Document fallen leaves", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Candy Time", description: "Create Halloween treat collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Ghost Hunt", description: "Train spooky decoration recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Fall Sky", description: "Document autumn clouds", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Scary Books", description: "Create spooky story collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Dark Nights", description: "Train low light recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Costume Make", description: "Document costume creation", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Party Prep", description: "Create Halloween party collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Monster Watch", description: "Train costume recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Haunted Scene", description: "Document spooky setups", category: .exploration, difficulty: .hard),
        DailyChallenge(title: "Trick Treat", description: "Create candy collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Night Magic", description: "Train Halloween night recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Spooky Walk", description: "Document decorated houses", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Halloween Fun", description: "Create party moment collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "October Review", description: "Review and organize October collections", category: .organization, difficulty: .hard),
        
        // NOVEMBER (30 days)
        DailyChallenge(title: "Thanksgiving Prep", description: "Train festive food recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Fall Finale", description: "Document last autumn colors", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Cozy Wear", description: "Create winter clothing collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Turkey Time", description: "Train thanksgiving meal recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Early Snow", description: "Document first snowfall", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Family Games", description: "Create indoor activity collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Harvest End", description: "Train late crop recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Frost Watch", description: "Document morning frost", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Recipe Box", description: "Create family recipe collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Winter Birds", description: "Train winter bird recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Gray Skies", description: "Document november weather", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Warm Drinks", description: "Create hot beverage collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Feast Prep", description: "Train cooking preparation recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Family Time", description: "Document gathering moments", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Table Setup", description: "Create thanksgiving decor collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Night Fall", description: "Train early darkness recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Bare Trees", description: "Document leafless trees", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Gratitude", description: "Create thankful moments collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Holiday Lights", description: "Train early decoration recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Weather Change", description: "Document temperature drops", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Feast Day", description: "Create thanksgiving collection", category: .organization, difficulty: .hard),
        DailyChallenge(title: "Dessert Time", description: "Train pie recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Family Fun", description: "Document holiday games", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Winter Prep", description: "Create cold weather collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Holiday Start", description: "Train festive decoration recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "First Ice", description: "Document ice formations", category: .exploration, difficulty: .hard),
        DailyChallenge(title: "Cozy Home", description: "Create indoor comfort collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Snow Watch", description: "Train snow pattern recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Evening Glow", description: "Document early lights", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "November Review", description: "Review and organize November collections", category: .organization, difficulty: .hard),
        
        // DECEMBER (31 days)
        DailyChallenge(title: "Winter Start", description: "Train winter scene recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Holiday Prep", description: "Document decoration process", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Light Show", description: "Create holiday light collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Snow Study", description: "Train snowflake recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Gift Wrap", description: "Document wrapping techniques", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Cookie Time", description: "Create baking collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Tree Trim", description: "Train ornament recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Winter Fun", description: "Document snow activities", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Festive Food", description: "Create holiday recipe collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Night Lights", description: "Train decoration recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Cozy Corner", description: "Document indoor spaces", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Winter Wear", description: "Create cold weather collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Ice Art", description: "Train frost pattern recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Holiday Joy", description: "Document celebration moments", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Sweet Treats", description: "Create dessert collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Winter Birds", description: "Train winter wildlife recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Snow Globe", description: "Document winter scenes", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Family Time", description: "Create tradition collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Star Light", description: "Train holiday light recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Eve Magic", description: "Document Christmas Eve", category: .exploration, difficulty: .hard),
        DailyChallenge(title: "Gift Time", description: "Create present collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Holiday Feast", description: "Train food recognition", category: .training, difficulty: .medium),
        DailyChallenge(title: "Winter Games", description: "Document family activities", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Cozy Days", description: "Create indoor activity collection", category: .organization, difficulty: .medium),
        DailyChallenge(title: "Snow Watch", description: "Train weather pattern recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Year End", description: "Document yearly highlights", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "New Plans", description: "Create resolution collection", category: .organization, difficulty: .easy),
        DailyChallenge(title: "Winter Sky", description: "Train night sky recognition", category: .training, difficulty: .hard),
        DailyChallenge(title: "Last Light", description: "Document year's end", category: .exploration, difficulty: .medium),
        DailyChallenge(title: "Memory Box", description: "Create year review collection", category: .organization, difficulty: .hard),
        DailyChallenge(title: "December Review", description: "Review and organize December collections", category: .organization, difficulty: .hard)
    ]
    
    public func getTodayChallenge() -> DailyChallenge {
        let calendar = Calendar.current
        let dayOfYear = calendar.ordinality(of: .day, in: .year, for: Date()) ?? 1
        let index = (dayOfYear - 1) % challenges.count
        return challenges[index]
    }
    
    public func isCompletedToday() -> Bool {
        let defaults = UserDefaults.standard
        let today = Calendar.current.startOfDay(for: Date())
        let lastCompleted = defaults.object(forKey: "lastCompletedChallenge") as? Date
        return lastCompleted == today
    }
    
    public func markCompleted() {
        let defaults = UserDefaults.standard
        defaults.set(Date(), forKey: "lastCompletedChallenge")
    }
    
    public func completeChallenge() {
        // Award points for challenge completion (e.g., 10 points)
        let currentPoints = UserDefaults.standard.integer(forKey: "totalPoints")
        let newPoints = currentPoints + 10
        UserDefaults.standard.set(newPoints, forKey: "totalPoints")
        
        // Update published points property on main thread
        DispatchQueue.main.async {
            self.totalPoints = newPoints
        }
        
        markCompleted()
        AchievementsManager.shared.updateAchievementsAfterChallenge()
    }
    
    public func incrementProgress() {
        if progress < 5 {
            progress += 1
            if progress == 5 {
                completeChallenge()
                // Optionally reset progress for next challenge cycle:
                progress = 0
            }
        }
    }
}
